# -*- coding: utf-8 -*-
"""Progress_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/149am5MtPz0SeSCbR50H7iusWGzf9rX9s

PROGRESS 4 (GROUP 10)
1. NURATHIRAH BINTI MUHAMAD ZAKI (A21EC3025)
2. YUSRA NADATUL ALYEEA BINTI YUSRAMIZAL (A21EC0151)
"""

from google.colab import files

# Upload the file
uploaded = files.upload()

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.feature_selection import RFE

# Load dataset
data = pd.read_csv('csv_result-Ovarian.csv')

# Exclude 'id'
if 'id' in data.columns:
    columns_to_exclude = ['id']
    data = data.drop(columns=columns_to_exclude, errors='ignore')


# Assuming the target column is the last column, separate features and target
X = data.iloc[:, :-1]  # Features (all columns kecuali last)
y = data.iloc[:, -1]  # Target variable (last column)


# Correlation-based feature selection
correlation_matrix = X.corr().abs()
upper_triangle = correlation_matrix.where(np.triu(np.ones(correlation_matrix.shape), k=1).astype(bool))
high_corr_features = [col for col in upper_triangle.columns if any(upper_triangle[col] > 0.95)]
X_selected = X.drop(columns=high_corr_features)



# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_selected, y, test_size=0.2, random_state=42)


# SVM-RFE
svm_classifier = SVC(kernel='linear')
num_top_genes = 5  # Specify the number of top genes to display
rfe = RFE(estimator=svm_classifier, n_features_to_select=num_top_genes)
rfe.fit(X_train, y_train)


# Get the selected features based
optimal_threshold = 0.8  # Adjust optimal value
selected_features = X_train.columns[rfe.support_]


# Display the top genes contributing to classification
top_genes = X[selected_features].max().sort_values(ascending=False)
print(f"Top {num_top_genes} Genes for Classification:")
print(top_genes)